### ISSUE TITLE
Project doesnt work

### ISSUE THREAD

**Issue by saifuddin123** [achen353/Face-Mask-Detector#1]
I tried this project and looks like its not tested. Are the requirements.txt having all needed libraries?

(fm1) pi@raspberrypi:~/Downloads/achen353/src $ python detect_mask_images.py -i example_images/pic1.jpg
python: can't open file 'detect_mask_images.py': [Errno 2] No such file or directory
(fm1) pi@raspberrypi:~/Downloads/achen353/src $ python detect_mask_image.py -i example_images/pic1.jpg
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "detect_mask_image.py", line 6, in <module>
    import cv2
  File "/home/pi/.virtualenvs/fm1/lib/python3.7/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import

**Comment by achen353** [comment]
Hi @saifuddin123 
Could you provide the version of your `numpy`?

**Comment by saifuddin123** [comment]
hi,
I used the requirements.txt provided. Below is the console log.

(fm1) pi@raspberrypi:~/Downloads/achen353/src $ python3 -c 'import tensorflow; print(tensorflow.__version__)'
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
2.4.0
(fm1) pi@raspberrypi:~/Downloads/achen353/src $ python3 -c 'import cv2; print(cv2.__version__)'
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pi/.virtualenvs/fm1/lib/python3.7/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
(fm1) pi@raspberrypi:~/Downloads/achen353/src $ python3 -c 'import numpy; print(numpy.__version__)'
1.19.2

**Comment by achen353** [comment]
I recommend reinstalling both cv2 and numpy and make sure you install `numpy==1.19.3`

**Comment by saifuddin123** [comment]
Hi, i tried with numpy 1.19.3, but no luck. DId a complete reinstall on a new venv. The issue is with incompatibility of opencv & tensor flow with the scipy v1.7.3 being installed along with scikit-learn 0.24.2.  I am no expert, but need this project working on RPI 4, i am using 32 bit. 
Any suggestions, pls?

**Comment by achen353** [comment]
What exactly is the package in conflict? You might be able to just use the most updated version of TensorFlow and OpenCV.
